# TCL File Generated by Component Editor 20.1
# Tue Nov 29 12:04:31 PST 2022
# DO NOT MODIFY


# 
# wordcopy "wordcopy" v1.0
#  2022.11.29.12:04:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module wordcopy
# 
set_module_property DESCRIPTION ""
set_module_property NAME wordcopy
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME wordcopy
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL wordcopy
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file wordcopy.sv SYSTEM_VERILOG PATH ../../2022w1-lab4-l1a-lab4-group03/task5/wordcopy.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point slave_1
# 
add_interface slave_1 avalon end
set_interface_property slave_1 addressUnits WORDS
set_interface_property slave_1 associatedClock clock
set_interface_property slave_1 associatedReset reset
set_interface_property slave_1 bitsPerSymbol 8
set_interface_property slave_1 burstOnBurstBoundariesOnly false
set_interface_property slave_1 burstcountUnits WORDS
set_interface_property slave_1 explicitAddressSpan 0
set_interface_property slave_1 holdTime 0
set_interface_property slave_1 linewrapBursts false
set_interface_property slave_1 maximumPendingReadTransactions 0
set_interface_property slave_1 maximumPendingWriteTransactions 0
set_interface_property slave_1 readLatency 0
set_interface_property slave_1 readWaitTime 1
set_interface_property slave_1 setupTime 0
set_interface_property slave_1 timingUnits Cycles
set_interface_property slave_1 writeWaitTime 0
set_interface_property slave_1 ENABLED true
set_interface_property slave_1 EXPORT_OF ""
set_interface_property slave_1 PORT_NAME_MAP ""
set_interface_property slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property slave_1 SVD_ADDRESS_GROUP ""

add_interface_port slave_1 slave_waitrequest waitrequest Output 1
add_interface_port slave_1 slave_address address Input 4
add_interface_port slave_1 slave_read read Input 1
add_interface_port slave_1 slave_readdata readdata Output 32
add_interface_port slave_1 slave_write write Input 1
add_interface_port slave_1 slave_writedata writedata Input 32
set_interface_assignment slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 32
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output 32

